### PR TITLE
PE-99 fix supervisor stop

### PR DESCRIPTION
**Pull request by reversefold**

### CODE REVIEW

**Comment by plathrop** [comment]
LGTM

**Comment by jib** [comment]
@reversefold: if you can make this available as an upstream patch, that might be worth ti (just a thought)

**Comment by reversefold** [comment]
Upstream supervisor doesn't have this init script, if there another place where I should try the PR?

**Comment by jib** [comment]
Ubuntu upstream - see first PR which adds the debian
dir to begin with.

On Mar 2, 2015, at 3:26 PM, Justin Patrin notifications@github.com wrote:

> Upstream supervisor doesn't have this init script, if there another place where I should try the PR?
> 
> —
> Reply to this email directly or view it on GitHub.

—
Entropy isn’t what it used to be...

**Pull request merged**
